# Generated by Django 6.0.7 on 2026-08-15 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SOP_Chat", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Site_Account",
            fields=[
                (
                    "site_name",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=45)),
                ("save_files", models.BooleanField(default=False)),
            ],
            options={
                "permissions": [
                    ("modify_sops", "Add/Drop Sops"),
                    ("modify_users", "change User settings"),
                ],
            },
        ),
        migrations.AlterField(
            model_name="document",
            name="uploaded_file",
            field=models.FileField(blank=True, null=True, upload_to="documents/"),
        ),
        migrations.AddField(
            model_name="document",
            name="site_name",
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sops",
                to="SOP_Chat.site_account",
            ),
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "username",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=45)),
                (
                    "ServiceLevel",
                    models.CharField(
                        choices=[
                            ("User", "User"),
                            ("Superuser", "Superuser"),
                            ("Admin", "Admin"),
                        ],
                        default="User",
                        max_length=10,
                    ),
                ),
                (
                    "site_name",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="SOP_Chat.site_account",
                    ),
                ),
            ],
        ),
    ]
