# Generated by Django 6.0.7 on 2026-08-15 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SOP_Chat", "0002_site_account_alter_document_uploaded_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="site_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sops",
                to="SOP_Chat.site_account",
            ),
        ),
    ]
